[inference]
    inference_path = 'data/inference/7845534b-bd6f-11f1-8d77-088fc33ba6cd/'
    job_name = 'Suan Rangsit Solar Check'

    input_folder = 'input'
    output_folder = 'output'
    tile_folder = 'input_tile'
    tile_size   = 512
    
    mlflow_registry = "solar-googleearth"
    mlflow_alias    = "current"
    
    batch_size  = 50
    mask_folder = 'mask_tile'
    mask_save_raw = true
    mask_raw_folder = 'mask_tile_raw'
    decide_threshold = 0.5

    redo = true
    n_thread    = -1 # -1 will use cpu_count()//2

    # 1 = 110000 KM
    # 0.1 = 11000 M
    # 0.01 = 1100 M
    # 0.001 = 110 M
    # 0.0001 = 11 M
    # 0.00001 = 1.1 M
    simplify_tolerance = 0.4
    minimum_area = 1 # remove when a polygon is less than this area (unit square meter), 0 means keep all shape
    average_panel_size = 2.541 # unit: square meter. This will use to estimate number of panels by `polygon_area`/`average_panel_size`.

    # Polygon attrubute
    ## area: sqaure meters
    ## adjusted_area: sqaure meters | `area` * `correct`
    ## no_panel: `adjusted_area` / `average_panel_size`
    # criterion: lower_bound < area <= upper_bound
# Google
    [[inference.panel]]
       size = "xs"
       lower_bound = 0
       upper_bound = 22
       correct = -7.71
    [[inference.panel]]
       size = "s"
       lower_bound = 22
       upper_bound = 30
       correct = -5.48
    [[inference.panel]]
       size = "m"
       lower_bound = 30
       upper_bound = 45
       correct = -4.80
    [[inference.panel]]
       size = "l"
        lower_bound = 45
        upper_bound = inf
        correct = 0.79

# # PLE NEO 30CM
#     [[inference.panel]]
#        size = "xs"
#        lower_bound = 0
#        upper_bound = 22
#        correct = -1.83
#     [[inference.panel]]
#        size = "s"
#        lower_bound = 22
#        upper_bound = 30
#        correct = -0.25
#     [[inference.panel]]
#        size = "m"
#        lower_bound = 30
#        upper_bound = 45
#        correct = 1.16
#     [[inference.panel]]
#        size = "l"
#         lower_bound = 45
#         upper_bound = inf
#         correct = 2.54

# # PLE 50CM
#     [[inference.panel]]
#        size = "xs"
#        lower_bound = 0
#        upper_bound = 22
#        correct = -3.19
#     [[inference.panel]]
#        size = "s"
#        lower_bound = 22
#        upper_bound = 30
#        correct = 5.84
#     [[inference.panel]]
#        size = "m"
#        lower_bound = 30
#        upper_bound = 45
#        correct = -1.47
#     [[inference.panel]]
#        size = "l"
#         lower_bound = 45
#         upper_bound = inf
#         correct = 9.75

